apiVersion: v1
kind: Service
metadata:
  name: conductor-placeholder
  namespace: wti-ai
spec:
  selector:
    app: conductor-placeholder
  ports:
    - name: http
      port: 80
      targetPort: 5678
      protocol: TCP
