apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: conductor
  namespace: wti-ai
spec:
  parentRefs:
    - name: conductor-gateway
  hostnames:
    - conductor.wti.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: conductor-placeholder
          port: 80
