apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    email: you@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: REPLACE_ME_GOOGLE_PROJECT_ID
            serviceAccountSecretRef:
              name: clouddns-dns01-svc-acct
              key: key.json
